### ISSUE TITLE
No module named "widget" error .

### ISSUE THREAD

**Issue by IamViditAgarwal** [pbugnion/ipywidgets_server#45]
Hi , I am using IPywidgets-server inside a Docker container. I have installed the Ipywidgets-server module by pip, added the python file in a folder from where it will be run (as per the documentation). Now I am running a bash script by the docker ENTRYPOINT that will execute the bash script having command "ipywidgets-server file_name: container" and then by docker networking I am exposing the port to be used at the client end. But I am facing a **Error:No module named file**. Can anyone help me?
PS: Any suggestion to it in a different way.
Thanks in Advance
Vidit

**Comment by pbugnion** [comment]
Thanks for raising this.

What you called `file_name` isn't actually a file_name, it's an importable module. I would probably have as entrypoint a shell script that cd's to the root directory of your module and run `ipywidgets-server` from there (just as you would on your own machine).

**Comment by IamViditAgarwal** [comment]
> Thanks for raising this.
> 
> What you called `file_name` isn't actually a file_name, it's an importable module. I would probably have as entrypoint a shell script that cd's to the root directory of your module and run `ipywidgets-server` from there (just as you would on your own machine).

Is there any way to customise ur ipywidgets html/css code ?

**Comment by pbugnion** [comment]
Can you share your Dockerfile? It's not obvious what's going wrong here.

**Comment by IamViditAgarwal** [comment]
> Can you share your Dockerfile? It's not obvious what's going wrong here.

The above error is resolved , But I am facing this error 
`require.min.js:1 Uncaught Error: Script error for "libwidgets"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.min.js:1)
    at HTMLScriptElement.onScriptError (require.min.js:1)`

**Comment by IamViditAgarwal** [comment]
Closing this issue , As its too late now.
